apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  # 类属性键；每一个键都映射到一个简单的值，仅仅支持键值对，不支持嵌套
  mysql: { { .Values.config.mysql } }
  redisIP: { { .Values.config.redisIP } }
  redisPassword: { { .Values.config.redisPassword } }

  pushRoomSubscribeNum: { { .Values.config.pushRoomSubscribeNum } }
  pushAllSubscribeNum: { { .Values.config.pushAllSubscribeNum } }


